### PR TITLE
[fix] dboissier#242 Cannot edit documents

### PR DESCRIPTION
**Pull request by cunneen**

### CODE REVIEW

**Comment by xstable** [comment]
@dboissier could you please merge this?
Thanks a lot.

**Comment by antonkomarev** [comment]
Could this tiny fix be merged? Readonly mode is not fun. Thanks for a great plugin!

**Comment by antonkomarev** [comment]
Update. Sadly, but this fix not working for me :\

**Comment by cunneen** [comment]
@antonkomarev it still works for me.

mongoplugin

**Comment by dboissier** [comment]
Hi,

sorry for the late response, I have some bandwidth and I will merge your PR ASAP

thanks

**Pull request merged**
